export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';

export const FETCH_THEME = 'FETCH_THEME';
export const FETCH_THEME_SUCCESS = 'FETCH_THEME_SUCCESS';
export const FETCH_THEME_ERROR = 'FETCH_THEME_ERROR';

export const FETCH_DEADLINE_LIST = 'FETCH_DEADLINE_LIST';
export const FETCH_DEADLINE_LIST_SUCCESS = 'FETCH_DEADLINE_LIST_SUCCESS';
export const FETCH_DEADLINE_LIST_ERROR = 'FETCH_DEADLINE_LIST_ERROR';

export const FETCH_DEADLINE = 'FETCH_DEADLINE';
export const FETCH_DEADLINE_SUCCESS = 'FETCH_DEADLINE_SUCCESS';
export const FETCH_DEADLINE_ERROR = 'FETCH_DEADLINE_ERROR';

export const ADD_DEADLINE = 'ADD_DEADLINE';
export const ADD_DEADLINE_SUCCESS = 'ADD_DEADLINE_SUCCESS';
export const ADD_DEADLINE_ERROR = 'ADD_DEADLINE_ERROR';

export const UPDATE_DEADLINE = 'UPDATE_DEADLINE';
export const UPDATE_DEADLINE_SUCCESS = 'UPDATE_DEADLINE_SUCCESS';
export const UPDATE_DEADLINE_ERROR = 'UPDATE_DEADLINE_ERROR';

export const DELETE_DEADLINE = 'DELETE_DEADLINE';
export const DELETE_DEADLINE_SUCCESS = 'DELETE_DEADLINE_SUCCESS';
export const DELETE_DEADLINE_ERROR = 'DELETE_DEADLINE_ERROR';

export const RESET_DEADLINE_STATUS = 'RESET_DEADLINE_STATUS';

export const DISMISS_NOTIFICATION = 'DISMISS_NOTIFICATION';
export const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION';

export const UPDATE_MODAL = 'UPDATE_MODAL';
